### ISSUE TITLE
CLI: Create working executable CLI app that show the core feature menu

### ISSUE THREAD

**Issue by wahyusa** [wahyusa/go-windows-proxy#2]
## Goals

Build executable file usually in `.exe` format that can be opened / run by users then showing the hard coded menu list and proxy status in CLI interface.

## TODO

- [x] Open code editor
- [x] Create or modify `main.go`
- [x] User can choose each menu
- [x] User can navigate back to home
- [x] User can choose to exit from menu or CTRL + C
- [x] Build the project in to executable file
- [x] Open it and expect it satisfied the task goals

## Personal notes

I believe it will using infinite loop.

I must use Golang native and internal package rather than using external package .

But if it takes too much time, better use external package and build fast, ship fast, get feedback fast.
