### ISSUE TITLE
CLI: Showing the app status and proxy status

### ISSUE THREAD

**Issue by wahyusa** [wahyusa/go-windows-proxy#6]
## Goals

Get and show proxy status / address in terminal app.

## TODO

- [x] Open code editor
- [x] Create or modify `main.go`
- [x] User can see their proxy status / address

## Personal notes

There is already CLI tools to do this something net blablabla

But I always found that it didn't work, sometimes it didn't change the proxy settings or address.

I already know that proxy address and settings are saved in Windows Registry / regedit.

This might be end up in to just executing specific command to get proxy settings information from windows registry.
