### ISSUE TITLE
CLI: Configurable proxy address

### ISSUE THREAD

**Issue by wahyusa** [wahyusa/go-windows-proxy#9]
## Goals

Users can configure their proxy address through a single command or a configuration file.

But not really directly modifying system proxy settings.

## TODO

- [x] Open code editor
- [x] Create or modify `main.go`
- [x] User can set their proxy through command with argument `wproxy addr=26.26.26.26:10809`
- [x] User can set their proxy setting ON / OFF (dummy) `wproxy on` `wproxy off` or `wproxy addr=26.26.26.26:10809 on` or similar things as long as it using native Go without external package.
- [x] Change the "Settings" menu ti "Address" User choose that menu then prompt to input proxy `addr`, after that user can go back to home to chose ON / OFF

## Personal notes

Possible problem to refactor

- Invalid address/URL
- Fake status in dummy config `wproxy.ini` vs Regedit value status, fixed by just add new status `Exact Status | Config Status"
